version: 2

project_name: <app_name>

changelog:
  disable: true

builds:
  - main: ./cmd/<app_name>
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/<org_name>/<app_name>/internal/cli.appVersion={{.Version}}
      - -X github.com/<org_name>/<app_name>/internal/cli.appCommit={{.Commit}}
      - -X github.com/<org_name>/<app_name>/internal/cli.appBuildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
